# Generated by Django 5.2.7 on 2025-11-01 23:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('due_date', models.DateField(default=datetime.date.today, verbose_name='Due Date')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completed')),
            ],
        ),
    ]
