# Generated by Django 5.2.8 on 2025-12-01 15:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, verbose_name='End Date')),
                ('state', models.CharField(choices=[('NS', 'Not Started'), ('IP', 'In Progress'), ('SB', 'In Standby'), ('FN', 'Finished')], default='NS', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Start Date')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('state', models.CharField(choices=[('NS', 'Not Started'), ('IP', 'In Progress'), ('SB', 'In Standby'), ('FN', 'Finished')], default='NS', max_length=2)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_tasks', to='tasks.project')),
            ],
        ),
    ]
