# Generated by Django 5.2.7 on 2025-11-02 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='details',
            field=models.URLField(blank=True, verbose_name='Details'),
        ),
    ]
